server:
  port: 8093

spring:
  application:
    name: redissonTest
  datasource:
    url: jdbc:mysql://101.43.118.58:3306/part?serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lwj123123
redis:
  popRedisSize: 1000
  available: true